services:
  we-meet-traefik:
    env_file: .env
    image: traefik:3.5.3
    container_name: we-meet-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./ssl:/etc/traefik/acme/
    networks:
      - we-meet-network

networks:
  we-meet-network:
    external: true