  entryPoints:
    web:
      address: ":80"
    websecure:
      address: ":443"

  providers:
    docker:
      exposedByDefault: false
    file:
      filename: /etc/traefik/traefik.yml
      watch: true

  certificatesResolvers:
    leResolver:
      acme:
        email: ${EMAIL}
        caServer: https://acme-v02.api.letsencrypt.org/directory
        tlsChallenge: {}

  log:
    level: DEBUG

  http:
    routers:
      we-meet-backend-https:
        rule: "Host(`${DOMAIN}`) && PathPrefix(`/api`)"
        service: we-meet-backend
        tls:
          options: {}
          certResolver: leResolver

      we-meet-frontend-https:
        rule: "Host(`${DOMAIN}`) && PathPrefix(`/`)"
        service: we-meet-frontend
        tls:
          options: {}
          certResolver: leResolver

      we-meet-backend-http:
        rule: "PathPrefix(`/api`)"
        service: we-meet-backend

      we-meet-frontend-http:
        rule: "PathPrefix(`/`)"
        service: we-meet-frontend

    services:
      we-meet-backend:
        loadBalancer:
          servers:
            - url: "http://we-meet-backend:3000"
          passHostHeader: true
      we-meet-frontend:
        loadBalancer:
          servers:
            - url: "http://we-meet-frontend:3003"
          passHostHeader: true
