  entryPoints:
    web:
      address: ":80"
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
    websecure:
      address: ":443"

  providers:
    docker:
      exposedByDefault: false

  log:
    level: DEBUG

  http:
    routers:
      we-meet-backend:
        entryPoints: [websecure]
        rule: "PathPrefix(`/api`)"
        service: we-meet-backend
        tls:
          certResolver: letsencrypt

      we-meet-frontend:
        entryPoints: [websecure]
        rule: "PathPrefix(`/`)"
        service: we-meet-frontend
        tls:
          certResolver: letsencrypt

    services:
      we-meet-backend:
        loadBalancer:
          servers:
            - url: "http://we-meet-backend:3000"

      we-meet-frontend:
        loadBalancer:
          servers:
            - url: "http://we-meet-frontend:3003"
