services:
  we-meet-coturn:
    env_file: ../.env
    image: coturn/coturn:4.6.2
    container_name: ${APP_NAME}-coturn
    ports:
      - "${TURN_PORT_UDP}:${TURN_PORT_UDP}/udp"
      - "${TURN_PORT_TCP}:${TURN_PORT_TCP}/tcp"
      - "${TURN_PORT_TLS}:${TURN_PORT_TLS}/tcp"
      - "49152-49200:49152-49200/udp"
    environment:
      - TURN_PUBLIC_IP=${TURN_PUBLIC_IP}
      - TURN_USERNAME=${TURN_USERNAME}
      - TURN_PASSWORD=${TURN_PASSWORD}
      - TURN_REALM=${TURN_REALM}
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    restart: always
