services:
  we-meet-coturn:
    image: coturn/coturn:4.6.3
    container_name: we-meet-coturn
    restart: unless-stopped
    ports:
      # STUN/TURN (стандартные порты)
      - "3478:3478"
      - "3478:3478/udp"
      # TLS-TURN (стандартный порт)
      - "5349:5349"
      - "5349:5349/udp"
      # RTP/RTCP relays
      - "49152-49200:49152-49200/udp"
    environment:
      # Автодетект IP (работает на VPS)
      DETECT_EXTERNAL_IP: "true"
      # Статический секрет для аутентификации TODO
#      STATIC_AUTH_SECRET: "${TURN_STATIC_AUTH_SECRET}"
      # Realm
      REALM: "${DOMAIN}"
    volumes:
      # Конфиг файл
      - "./turnserver.conf:/etc/coturn/turnserver.conf:ro"
      # База данных и логи
      - "./coturn-data:/var/lib/coturn"
      - "./coturn-logs:/var/log"
      - ../ssl:/etc/letsencrypt:ro
    networks:
      - we-meet-network

volumes:
  coturn-data:
  coturn-logs:

networks:
  we-meet-network:
    external: true